name: "Add notification"
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  add-notification:
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - name: Build
        run: |
          npm ci
          npm run build

      - name: Run
        uses: ./
        with:
          path: 'notifications/notification.md'
          file: "README.md"

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Workm8
          author_email: workm8@users.noreply.github.com
          message: 'Added Notification'
          add: 'README.md'

     