name: "Add notification"
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  add-notification:
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - name: Build
        run: |
          npm ci
          npm run build

      - name: Run
        uses: ./
        with:
          path: 'notifications/notification.md'
          file: "README.md"

      - name: Commit Notification
        run: |
          git config --global user.name 'Workm8'
          git config --global user.email 'workm8@users.noreply.github.com'
          git commit -am "Added README.md notification"
          git push